"""
OWL 2 DL Import for ADL Lite.

Parses OWL 2 DL Turtle (and basic RDF/XML) back to ADLDocument / EventChain.
This completes the bidirectional alignment (FW1): ADL ↔ OWL.

Paper §6.2: "OWL 2 export is available for interoperability with Protégé
and formal reasoners." The import path enables round-trip validation:
export → import → verify integrity.
"""

from __future__ import annotations

import re

from .models import (
    ADLDocument,
    ADLFrontMatter,
    ADLType,
    DiscoveryStatus,
    Event,
    EventType,
)

ADL_NS = "http://adl-lite.org/ontology/"


def _extract_turtle_value(line: str, predicate: str) -> str | None:
    """Extract a quoted literal value after a predicate in a Turtle line."""
    pattern = re.escape(predicate) + r'\s+"([^"]+)"'
    match = re.search(pattern, line)
    if match:
        return match.group(1)
    return None


def _extract_turtle_uri(line: str, predicate: str) -> str | None:
    """Extract a URI value after a predicate in a Turtle line."""
    pattern = re.escape(predicate) + r"\s+([a-zA-Z0-9_:/-]+)"
    match = re.search(pattern, line)
    if match:
        return match.group(1)
    return None


def parse_owl_turtle(turtle_str: str) -> ADLDocument:
    """
    Parse OWL 2 DL Turtle (as generated by `owl_export.document_to_owl_turtle`)
    back into an ADLDocument.

    This is a format-specific parser: it assumes the Turtle was produced by
    ADL Lite's own export, so it can rely on predictable structure rather
    than a full generic Turtle parser. For arbitrary OWL, use rdflib.
    """
    lines = [
        line.strip()
        for line in turtle_str.splitlines()
        if line.strip() and not line.strip().startswith("@prefix")
    ]

    # Find concept declaration line
    concept_id = None
    adl_type = ADLType.CONCEPT
    for line in lines:
        if " a " in line:
            parts = line.split(" a ")
            concept_id = parts[0].replace("adl:", "").strip()
            type_part = parts[1].split(";")[0].replace("adl:", "").strip()
            if any(type_part == e.value for e in ADLType):
                adl_type = ADLType(type_part)
            break

    if not concept_id:
        raise ValueError("Could not find concept declaration in Turtle input")

    # Collect all lines for the concept block (until first .)
    status = DiscoveryStatus.PROVISIONAL
    confidence = 0.0
    validators: list[str] = []
    domain = ""
    scope = "public"

    for line in lines:
        if "adl:hasStatus" in line:
            uri = _extract_turtle_uri(line, "adl:hasStatus")
            if uri:
                status_str = uri.split("/")[-1]
                if any(status_str == e.value for e in DiscoveryStatus):
                    status = DiscoveryStatus(status_str)
        elif "adl:hasConfidence" in line:
            val = _extract_turtle_value(line, "adl:hasConfidence")
            if val:
                confidence = float(val)
        elif "adl:validatedBy" in line:
            uri = _extract_turtle_uri(line, "adl:validatedBy")
            if uri:
                validators.append(uri.split("/")[-1])
        elif "adl:hasDomain" in line:
            domain = _extract_turtle_value(line, "adl:hasDomain") or domain
        elif "adl:hasScope" in line:
            scope_val = _extract_turtle_value(line, "adl:hasScope")
            if scope_val:
                scope = scope_val

    # Parse events
    events: list[Event] = []
    event_id = None
    event_actor = ""
    event_timestamp = ""

    for line in lines:
        if "adl:event/" in line and " a adl:Event" in line:
            # Start of event block
            event_id = line.split("adl:event/")[1].split(" ")[0].strip()
            event_actor = ""
            event_timestamp = ""
        elif "adl:hasActor" in line and event_id:
            val = _extract_turtle_value(line, "adl:hasActor")
            if val:
                event_actor = val
        elif "adl:hasTimestamp" in line and event_id:
            val = _extract_turtle_value(line, "adl:hasTimestamp")
            if val:
                event_timestamp = val

        if event_id and event_actor and event_timestamp:
            # Infer event type from context (default VALIDATE for re-imported events)
            events.append(
                Event(
                    concept_id=concept_id,
                    event_type=EventType.VALIDATE,
                    actor=event_actor,
                    payload={"confidence": confidence},
                    timestamp=event_timestamp,
                )
            )
            event_id = None
            event_actor = ""
            event_timestamp = ""

    # Build document
    front_matter = ADLFrontMatter(
        adl_type=adl_type,
        adl_id=concept_id,
        status=status,
        confidence=confidence,
        validators=validators,
        domain=domain,
        scope=scope,
    )

    return ADLDocument(
        front_matter=front_matter,
        markdown_body="",
    )


def parse_owl_rdfxml(rdfxml_str: str) -> ADLDocument:
    """
    Parse OWL 2 DL RDF/XML (as generated by `owl_export.document_to_owl_rdfxml`)
    back into an ADLDocument.

    Uses xml.etree.ElementTree for lightweight parsing without external deps.
    """
    import xml.etree.ElementTree as ET

    root = ET.fromstring(rdfxml_str)

    # Namespace map
    ns = {
        "owl": "http://www.w3.org/2002/07/owl#",
        "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
        "adl": ADL_NS,
    }

    # Find concept individual
    concept_elem = None
    for ind in root.findall("owl:NamedIndividual", ns):
        about = ind.get("{http://www.w3.org/1999/02/22-rdf-syntax-ns#}about", "")
        if "event/" not in about:
            concept_elem = ind
            break

    if concept_elem is None:
        raise ValueError("Could not find concept individual in RDF/XML")

    concept_id = concept_elem.get("{http://www.w3.org/1999/02/22-rdf-syntax-ns#}about", "").replace(
        ADL_NS, ""
    )

    # Type
    adl_type = ADLType.CONCEPT
    type_res = concept_elem.find("rdf:type", ns)
    if type_res is not None:
        type_uri = type_res.get("{http://www.w3.org/1999/02/22-rdf-syntax-ns#}resource", "")
        type_str = type_uri.replace(ADL_NS, "")
        if any(type_str == e.value for e in ADLType):
            adl_type = ADLType(type_str)

    # Status
    status = DiscoveryStatus.PROVISIONAL
    status_elem = concept_elem.find("adl:hasStatus", ns)
    if status_elem is not None:
        status_uri = status_elem.get("{http://www.w3.org/1999/02/22-rdf-syntax-ns#}resource", "")
        status_str = status_uri.split("/")[-1]
        if any(status_str == e.value for e in DiscoveryStatus):
            status = DiscoveryStatus(status_str)

    # Confidence
    confidence = 0.0
    conf_elem = concept_elem.find("adl:hasConfidence", ns)
    if conf_elem is not None and conf_elem.text:
        confidence = float(conf_elem.text)

    # Validators
    validators = []
    for val_elem in concept_elem.findall("adl:validatedBy", ns):
        val_uri = val_elem.get("{http://www.w3.org/1999/02/22-rdf-syntax-ns#}resource", "")
        validators.append(val_uri.split("/")[-1])

    # Domain
    domain = ""
    domain_elem = concept_elem.find("adl:hasDomain", ns)
    if domain_elem is not None and domain_elem.text:
        domain = domain_elem.text

    # Scope
    scope = "public"
    scope_elem = concept_elem.find("adl:hasScope", ns)
    if scope_elem is not None and scope_elem.text:
        scope = scope_elem.text

    # Events
    events = []
    for event_ind in root.findall("owl:NamedIndividual", ns):
        about = event_ind.get("{http://www.w3.org/1999/02/22-rdf-syntax-ns#}about", "")
        if "event/" not in about:
            continue

        about.replace(f"{ADL_NS}event/", "")
        actor_elem = event_ind.find("adl:hasActor", ns)
        actor = actor_elem.text if actor_elem is not None and actor_elem.text else "unknown"
        ts_elem = event_ind.find("adl:hasTimestamp", ns)
        timestamp = ts_elem.text if ts_elem is not None and ts_elem.text else ""

        events.append(
            Event(
                concept_id=concept_id,
                event_type=EventType.VALIDATE,
                actor=actor,
                payload={"confidence": confidence},
                timestamp=timestamp,
            )
        )

    front_matter = ADLFrontMatter(
        adl_type=adl_type,
        adl_id=concept_id,
        status=status,
        confidence=confidence,
        validators=validators,
        domain=domain,
        scope=scope,
    )

    return ADLDocument(
        front_matter=front_matter,
        markdown_body="",
    )
