"""
OWL 2 DL Export for ADL Lite.

Exports EventChain data to OWL 2 DL format (RDF/XML or Turtle).
Used for interoperability with semantic-web tools and formal reasoners.

Paper §6.2: "OWL 2 export is available for interoperability with Protégé
and formal reasoners."
"""

from __future__ import annotations

from xml.etree.ElementTree import Element, SubElement, tostring

from .models import ADLDocument, DiscoveryStatus, EventType

OWL_NS = "http://www.w3.org/2002/07/owl#"
RDF_NS = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
RDFS_NS = "http://www.w3.org/2000/01/rdf-schema#"
ADL_NS = "http://adl-lite.org/ontology/"


def _make_uri(concept_id: str) -> str:
    """Build a URI for a concept."""
    return f"{ADL_NS}{concept_id}"


def _status_to_uri(status: DiscoveryStatus) -> str:
    """Map ADL status to OWL individual URI."""
    return f"{ADL_NS}status/{status.value}"


def _event_type_to_uri(event_type: EventType) -> str:
    """Map ADL event type to OWL property URI."""
    return f"adl:has{event_type.value.capitalize()}Event"


def document_to_owl_rdfxml(doc: ADLDocument) -> str:
    """
    Convert an ADLDocument to OWL 2 DL RDF/XML.

    Returns an XML string suitable for import into Protégé or other OWL tools.
    """
    root = Element(
        "rdf:RDF",
        {
            "xmlns:owl": OWL_NS,
            "xmlns:rdf": RDF_NS,
            "xmlns:rdfs": RDFS_NS,
            "xmlns:adl": ADL_NS,
        },
    )

    # Ontology declaration
    onto = SubElement(root, "owl:Ontology")
    onto.set("rdf:about", ADL_NS)

    # Concept individual
    concept_uri = _make_uri(doc.adl_id)
    concept = SubElement(root, "owl:NamedIndividual")
    concept.set("rdf:about", concept_uri)

    # Type assertion
    type_assertion = SubElement(concept, "rdf:type")
    type_assertion.set("rdf:resource", f"{ADL_NS}{doc.front_matter.adl_type.value}")

    # Status
    status_elem = SubElement(concept, "adl:hasStatus")
    status_elem.set("rdf:resource", _status_to_uri(doc.front_matter.status))

    # Confidence
    confidence_elem = SubElement(concept, "adl:hasConfidence")
    confidence_elem.set("rdf:datatype", "http://www.w3.org/2001/XMLSchema#float")
    confidence_elem.text = str(doc.front_matter.confidence)

    # Validators
    for validator in doc.front_matter.validators:
        val_elem = SubElement(concept, "adl:validatedBy")
        val_elem.set("rdf:resource", f"{ADL_NS}agent/{validator}")

    # Domain
    if doc.front_matter.domain:
        domain_elem = SubElement(concept, "adl:hasDomain")
        domain_elem.text = doc.front_matter.domain

    # Scope
    scope_elem = SubElement(concept, "adl:hasScope")
    scope_elem.text = doc.front_matter.scope

    # Events (from chain)
    for event in doc.event_chain.events:
        event_uri = f"{ADL_NS}event/{event.event_id}"
        event_ind = SubElement(root, "owl:NamedIndividual")
        event_ind.set("rdf:about", event_uri)

        event_type = SubElement(event_ind, "rdf:type")
        event_type.set("rdf:resource", f"{ADL_NS}Event")

        event_concept = SubElement(event_ind, "adl:belongsTo")
        event_concept.set("rdf:resource", concept_uri)

        event_actor = SubElement(event_ind, "adl:hasActor")
        event_actor.text = event.actor

        event_ts = SubElement(event_ind, "adl:hasTimestamp")
        event_ts.text = event.timestamp

        # Link concept to event
        prop = _event_type_to_uri(event.event_type)
        event_prop = SubElement(concept, prop)
        event_prop.set("rdf:resource", event_uri)

    # Add comment
    comment = SubElement(onto, "rdfs:comment")
    comment.text = f"OWL export of ADL concept {doc.adl_id} generated by adl-lite"

    return tostring(root, encoding="unicode")


def document_to_owl_turtle(doc: ADLDocument) -> str:
    """
    Convert an ADLDocument to OWL 2 DL Turtle syntax.

    Returns a Turtle string suitable for import into Protégé or other OWL tools.
    """
    lines: list[str] = [
        "@prefix owl: <http://www.w3.org/2002/07/owl#> .",
        "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .",
        "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .",
        "@prefix adl: <http://adl-lite.org/ontology/> .",
        "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
        "",
        f"adl:{doc.adl_id} a adl:{doc.front_matter.adl_type.value} ;",
        f"    adl:hasStatus adl:status/{doc.front_matter.status.value} ;",
        f'    adl:hasConfidence "{doc.front_matter.confidence}"^^xsd:float ;',
    ]

    for validator in doc.front_matter.validators:
        lines.append(f"    adl:validatedBy adl:agent/{validator} ;")

    if doc.front_matter.domain:
        lines.append(f'    adl:hasDomain "{doc.front_matter.domain}" ;')

    lines.append(f'    adl:hasScope "{doc.front_matter.scope}" .')
    lines.append("")

    for event in doc.event_chain.events:
        lines.append(f"adl:event/{event.event_id} a adl:Event ;")
        lines.append(f"    adl:belongsTo adl:{doc.adl_id} ;")
        lines.append(f'    adl:hasActor "{event.actor}" ;')
        lines.append(f'    adl:hasTimestamp "{event.timestamp}"^^xsd:dateTime .')
        lines.append("")

    return "\n".join(lines)


def export_owl(doc: ADLDocument, format: str = "turtle") -> str:
    """
    Export an ADLDocument to OWL 2 DL.

    Args:
        doc: The ADLDocument to export
        format: "turtle" or "rdfxml"

    Returns:
        OWL serialization as a string
    """
    if format == "rdfxml":
        return document_to_owl_rdfxml(doc)
    return document_to_owl_turtle(doc)
